3 search
IvanGit2021/My-Series-List pull request #3
Opened 2021-12-27 15:13 UTC by IvanGit2021

Load screen with List of 100 Most Popular Series ordered by Name (test best results from API);

Use Search View to filter Series from API, ordered by Name;

If no results are found, show TextView with message “No results”;

Each series contains a button to add to Series List or remove if already added (checkmark ☑);

When a Series is clicked, a Series Details screen is opened

2022-01-03 10:03 UTC, andre-exd requested changes

2022-01-03 10:03 UTC, andre-exd commented on My Series List/My Series List/Model/Repository/SeriesRepository.swift
> +    func insertSeries(series: Api.Series) {
Please consider adding method insertSeries() below existing methods in order to ready changes in historical way

2022-01-03 10:03 UTC, andre-exd commented on My Series List/My Series List/My_Series_List.xcdatamodeld/My_Series_List.xcdatamodel/contents
> +        <attribute name="isSaved" optional="YES" attributeType="Boolean" usesScalarValueType="YES"/>
Is it possible to reorder attributes in order to have same order as in Series from SeriesModel?

2022-01-03 10:03 UTC, andre-exd commented on My Series List/My Series List/View/SearchView/SearchCollectionViewCell.swift
> +
Remove extra lines

2022-01-03 10:03 UTC, andre-exd commented on My Series List/My Series List/View/SearchView/SearchController.swift
> +    func listError(_ error: Error) {
Move listError below existing listEmpty

2022-01-03 10:03 UTC, andre-exd commented on My Series List/My Series List/View/SearchView/SearchController.swift
> +
Remove extra lines

2022-01-03 10:03 UTC, andre-exd commented on My Series List/My Series List/Model/Repository/SeriesRemoteDataSource.swift
> -    let url = "https://api.themoviedb.org/3/search/tv?api_key=0fbc13d4f4bb3dcc23cb30a1a289d426&language=en-US&page=1&include_adult=false&query="
Can you consider 2 different variables for url?
apiUrl = "https://api.themoviedb.org/3/"
apiParameters = "api_key=fcad3621f48126f0c82cbfb62dc59904"
If you need to define a searchUrl you can concatenate apiUrl with "search/movie?query=" and add apiParameters
Something like this: searchUrl = apiURL + "search/movie?query=" + search + "&" + apiParameters

2022-01-03 10:03 UTC, andre-exd commented on My Series List/My Series List/Model/Repository/SeriesRepository.swift
> +        seriesLocalDataSource.insertSeries(series: series) { results in
Fix formatting

2022-01-03 10:03 UTC, andre-exd commented on My Series List/My Series List/View/SearchView/SearchPresenter.swift
> +                            self.seriesRepository.deleteSeries(series: series) { results in
Seems like results is not being used. Is there a better way to specify that the parameters are not being used?

2022-01-03 10:03 UTC, andre-exd commented on My Series List/My Series List/View/SearchView/SearchPresenter.swift
> +                for seriesA in seriesCoreData {
Can you use a better name for distinguishing Series? Given that seriesArray is the parameter of the method, those Series could be called series as it is the main purpose of the method updating some of those

2022-01-03 10:03 UTC, andre-exd commented on My Series List/My Series List/View/SearchView/SearchPresenter.swift
> +                        if seriesA.id == seriesB.id! {
You should use break in order to skip checking all values.
In my understanding you might even want to switch the order of the for cycles in order to iterate each item from seriesArray once and for each one checking values on repository

2022-01-03 17:37 UTC, andre-exd reviewed
Looks good. Please solve conflicts with main

2022-01-03 18:52 UTC, IvanGit2021 commented on My Series List/My Series List/My_Series_List.xcdatamodeld/My_Series_List.xcdatamodel/contents
> +        <attribute name="isSaved" optional="YES" attributeType="Boolean" usesScalarValueType="YES"/>
I found that Xcode doesn't allow to change the order of the attributes and it presents it sorted by alphabetic name, would be a possibility to change the Model instead ?

2022-01-05 10:02 UTC, andre-exd commented on My Series List/My Series List/My_Series_List.xcdatamodeld/My_Series_List.xcdatamodel/contents
> +        <attribute name="isSaved" optional="YES" attributeType="Boolean" usesScalarValueType="YES"/>
I was not aware of this. Keep it as it is then

2022-01-07 15:54 UTC, andre-exd approved these changes

2022-01-07 16:12 UTC, merged